### ISSUE TITLE
request for Extract_Users_LongitudinalProfile.py

### ISSUE THREAD

**Issue by Sholehmousavipour** [tgrippa/flickr_api_scripts#2]
Hi there,
I need to extract photos of a catchment for mapping. I need the lat and long as well as taken date. I have a shapefile of my case study. 
I know Python basically and I can't run the existing code or improve that.
Could you please guide me about that.

Cheers

**Comment by tgrippa** [comment]
Sorry but I cannot guide you in the run/modification of this code if you don't have a strong fondation on Python :/

**Comment by Sholehmousavipour** [comment]
Thanks,
I need to hire research assistance to help me. 
Do u know any python programmer that helps me online about that?

**Comment by tgrippa** [comment]
No I don't know someone like that, sorrry.

**Comment by Sholehmousavipour** [comment]
Thanks
